Feat/intake
Choate-Robotics/7407-DriveCode-Crescendo pull request #54
Opened 2024-02-07 22:07 UTC by e-bauman

2024-02-08 03:01 UTC, Inspirol requested changes
good otherwise

2024-02-08 03:01 UTC, Inspirol commented on subsystem/intake.py
>              can_id=config.outer_intake_back_id,
Make sure to check the parameter that enables brushed motors

2024-02-08 22:09 UTC, mbardoe commented
@e-bauman  Here are a few notes from our code Review

Put config in the config file
Double check motor config syntax

Outer motor back and front should just be outer_motor
Delete commented code please
Line 74 creating variable is redundant, just return
What is the point of idle_speed?

2024-02-11 17:39 UTC, e-bauman commented
idle_speed is because we are going to have the intake idly spinning when it is not actively intaking. When we don't have a note, it will idly spin in and increase in speed when we detect a note, when we do have a note, it will idly spin out so we don't accidentally pick up another note.

In the detect_note function, I am not making a new variable, I am changing the state of the subsystem variable note_in_intake.

I made the other changes from the code review

2024-02-11 18:15 UTC, Inspirol approved these changes
awesome work

2024-02-11 18:17 UTC, mbardoe approved these changes

2024-02-11 18:36 UTC, merged